pragmaticSlots = {
    "vs20sugarrush": { name: "Sugar Rush", bonus_buy: 100 },
    "vs25wolfgold": { name: "Wolf Gold" },
    "vs20olympgate": { name: "Gates of Olympus", bonus_buy: 100 },
    "vs20fruitsw": { name: "Sweet Bonanza", bonus_buy: 100 },
    "vswaysdogs": { name: "The Dog House Megaways", bonus_buy: 100 },
    "vs20fparty2": { name: "Fruit Party 2", bonus_buy: 100 },
    "vs20doghouse": { name: "The Dog House" },
    "vs20starlight": { name: "Starlight Princess", bonus_buy: 100 },
    "vs25wildspells": { name: "Wild Spells" },
    "vs20bchprty": { name: "Wild Beach Party", bonus_buy: 100 },
    "vs20rhino": { name: "Great Rhino" },
    "vs40pirate": { name: "Pirate Gold", bonus_buy: 0 },
    "vs20goldfever": { name: "Gems Bonanza", bonus_buy: 100 },
    "vs25mustang": { name: "Mustang Gold" },
    "vswaysbufking": { name: "Buffalo King Megaways", bonus_buy: 100 },
    "vs25scarabqueen": { name: "John Hunter and the Tomb of the Scarab Queen" },
    "vs1600drago": { name: "Drago - Jewels of Fortune", bonus_buy: 100 },
    "vs10bookoftut": { name: "John Hunter And The Book Of Tut", bonus_buy: 100 },
    "vs20cleocatra": { name: "Cleocatra", bonus_buy: 100 },
    "vs20midas": { name: "The Hand of Midas", bonus_buy: [100, 200, 300] },
    "vs243fortune": { name: "Caishen's Gold", bonus_buy: [] },
    "vs15diamond": { name: "Diamond Strike", bonus_buy: [] },
    "vs25chilli": { name: "Chilli Heat", bonus_buy: [] },
    "vs5aztecgems": { name: "Aztec Gems", bonus_buy: [] },
    "vs10fruity2": { name: "Extra Juicy", bonus_buy: [] },
    "vs20egypttrs": { name: "Egyptian Fortunes", bonus_buy: [] },
    "vs243lionsgold": { name: "5 Lions Gold", bonus_buy: [] },
    "vs9hotroll": { name: "Hot Chilli", bonus_buy: [] },
    "vs20chicken": { name: "The Great Chicken Escape", bonus_buy: [] },
    "vs1fortunetree": { name: "Tree of Riches", bonus_buy: [] },
    "vs10firestrike": { name: "Fire Strike", bonus_buy: [] },
    "vs20sbxmas": { name: "Sweet Bonanza Xmas", bonus_buy: [ 100 ] },
    "vs40wildwest": { name: "Wild West Gold", bonus_buy: [ 100 ] },
    "vswaysrhino": { name: "Great Rhino Megaways", bonus_buy: 100 },
    "vswayswerewolf": { name: "Curse of the Werewolf Megaways", bonus_buy: [ 100 ] },
    "vs50pixie": { name: "Pixie Wings", bonus_buy: [] },
    "vs25gladiator": { name: "Wild Gladiators", bonus_buy: [] },
    "vs20vegasmagic": { name: "Vegas Magic", bonus_buy: [] },
    "vs7fire88": { name: "Fire 88", bonus_buy: [] },
    "vs5joker": { name: "Joker's Jewels", bonus_buy: [] },
    "vs10madame": { name: "Madame Destiny", bonus_buy: [] },
    "vs1024butterfly": { name: "Jade Butterfly", bonus_buy: [] },
    "vs20leprexmas": { name: "Leprechaun Carol", bonus_buy: [] },
    "vs10vampwolf": { name: "Vampires vs Wolves", bonus_buy: [] },
    "vs20hercpeg": { name: "Hercules and Pegasus", bonus_buy: [] },
    "vs20aladdinsorc": { name: "Aladdin and the Sorcerer", bonus_buy: [] },
    "vs1masterjoker": { name: "Master Joker", bonus_buy: [] },
    "vs40frrainbow": { name: "Fruit Rainbow", bonus_buy: [] },
    "vs75bronco": { name: "Bronco Spirit", bonus_buy: [] },
    "vs25pyramid": { name: "Pyramid King", bonus_buy: [] },
    "vs10goldfish": { name: "Fishin Reels", bonus_buy: [] },
    "vs7monkeys": { name: "7 Monkeys", bonus_buy: [] },
    "vs50aladdin": { name: "3 Genie Wishes", bonus_buy: [] },
    "vs25safari": { name: "Hot Safari", bonus_buy: [] },
    "vs243crystalcave": { name: "Magic Crystals", bonus_buy: [] },
    "vs50kingkong": { name: "Mighty Kong", bonus_buy: [] },
    "vs50hercules": { name: "Hercules Son of Zeus", bonus_buy: [] },
    "vs25queenofgold": { name: "Queen of gold", bonus_buy: [] },
    "vs1024atlantis": { name: "Queen of Atlantis", bonus_buy: [] },
    "vs25kingdoms": { name: "3 Kingdoms – Battle of Red Cliffs", bonus_buy: [] },
    "vs4096jurassic": { name: "Jurassic Giants", bonus_buy: [] },
    "vs7pigs": { name: "7 Piggies", bonus_buy: [] },
    "vs25pandagold": { name: "Panda's Fortune", bonus_buy: [] },
    "vs15fairytale": { name: "Fairytale Fortune", bonus_buy: [] },
    "vs9madmonkey": { name: "Monkey Madness", bonus_buy: [] },
    "vs243lions": { name: "5 Lions", bonus_buy: [] },
    "vs25champ": { name: "The Champions", bonus_buy: [] },
    "vs25peking": { name: "Peking Luck", bonus_buy: [] },
    "vs20leprechaun": { name: "Leprechaun Song", bonus_buy: [] },
    "vs9chen": { name: "Master Chen's Fortune", bonus_buy: [] },
    "vs18mashang": { name: "Treasure Horse", bonus_buy: [] },
    "vs243caishien": { name: "Caishen's Cash", bonus_buy: [] },
    "vs243mwarrior": { name: "Monkey Warrior", bonus_buy: [] },
    "vs8magicjourn": { name: "Magic Journey", bonus_buy: [] },
    "vs4096mystery": { name: "Mysterious", bonus_buy: [] },
    "vs75empress": { name: "Golden Beauty", bonus_buy: [] },
    "vs243dancingpar": { name: "Dance Party", bonus_buy: [] },
    "vs25kfruit": { name: "Aztec Bonanza", bonus_buy: [] },
    "vs40madwheel": { name: "The Wild Machine", bonus_buy: [] },
    "vs10threestar": { name: "Three Star Fortune", bonus_buy: [] },
    "vs117649starz": { name: "Starz Megaways", bonus_buy: [] },
    "vs40streetracer": { name: "Street Racer", bonus_buy: [] }, // ???
    "vs20rhinoluxe": { name: "Great Rhino Deluxe" },
    "vs9aztecgemsdx": { name: "Aztec Gems Deluxe", bonus_buy: [] },
    "vs576treasures": { name: "Wild Wild Riches", bonus_buy: [] },
    "vswayshive": { name: "Star Bounty", bonus_buy: [ 75 ] },
    "vs25walker": { name: "Wild Walker", bonus_buy: [] },
    "vs40pirgold": { name: "Pirate Gold Deluxe", bonus_buy: [ 100 ] },
    "vs10cowgold": { name: "Cowboys Gold", bonus_buy: [] },
    "vs20xmascarol": { name: "Christmas Carol Megaways", bonus_buy: [ 100 ] },
    "vs40spartaking": { name: "Spartan King", bonus_buy: [] },
    "vswayslions": { name: "5 Lions Megaways", bonus_buy: [ 100 ] },
    "vs20emptybank": { name: "Empty the Bank", bonus_buy: [ 80 ] },
    "vs25dwarves_new": { name: "Dwarven Gold Deluxe", bonus_buy: [] },
    "vs25newyear": { name: "Lucky New Year", bonus_buy: [] },
    "vs10mayangods": { name: "John Hunter and the Mayan Gods", bonus_buy: [] },
    "vs20honey": { name: "Honey Honey Honey", bonus_buy: [] },
    "vswaysmadame": { name: "Madame Destiny Megaways", bonus_buy: [ 100 ] },
    "vs20wildboost": { name: "Wild Booster", bonus_buy: [ 75 ] },
    "vs25pantherqueen": { name: "Panther Queen", bonus_buy: [] },
    "": { name: "John Hunter and the Aztec Treasure", bonus_buy: [] },
    "vs10bookviking": { name: "Book of Vikings", bonus_buy: [ 100 ] },
    "vs20chickdrop": { name: "Chicken Drop", bonus_buy: [ 100 ] },
    "vs20amuleteg": { name: "Fortune of Giza", bonus_buy: [] },
    "vs20bchprty": { name: "Wild Beach Party", bonus_buy: [ 100 ] },
    "vswayszombcarn": { name: "Zombie Carnival", bonus_buy: [ 80 ] },
    "vs1600drago": { name: "Drago - Jewels of Fortune", bonus_buy: [ 100 ] },
    "vswayshammthor": { name: "Power of Thor Megaways", bonus_buy: [ 100 ] },
    "vs20magicpot": { name: "The Magic Cauldron", bonus_buy: [] },
    "vs25rio": { name: "Heart of Rio", bonus_buy: [] },
    "vs20farmfest": { name: "Barn Festival", bonus_buy: [ 100 ] },
    "vs50northgard": { name: "North Guardians", bonus_buy: [ 100 ] },
    "vs25copsrobbers": { name: "Cash Patrol", bonus_buy: [] },
    "vs10chkchase": { name: "Chicken Chase", bonus_buy: [] },
    "vs10firestrike2": { name: "Fire Strike 2", bonus_buy: [] },
    "vs10egrich": { name: "Queen of Gods", bonus_buy: [] },
    "vs1024lionsd": { name: "5 Lions Dance", bonus_buy: [] },
    "vs10wildtut": { name: "Mysterious Egypt", bonus_buy: [ 100 ] },
    "vs5drmystery": { name: "Dragon Kingdom Eyes of Fire", bonus_buy: [] },
    "vs25hotfiesta": { name: "Hot Fiesta", bonus_buy: [ 100 ] },
    "vs25btygold": { name: "Bounty Gold", bonus_buy: [] },
    "vs20superx": { name: "Super X", bonus_buy: [] },
    "vs20ultim5": { name: "The Ultimate 5", bonus_buy: [] },
    "vs50mightra": { name: "Might of Ra", bonus_buy: [] },
    "vs20drtgold": { name: "Drill That Gold", bonus_buy: [] },
    "vs20mustanggld2": { name: "Clover Gold", bonus_buy: [] },
    "vs20gobnudge": { name: "Goblin Heist Powernudge", bonus_buy: [ 100 ] },
    "vs20stickysymbol": { name: "The Great Stick-Up", bonus_buy: [] },
    "vswayswildwest": { name: "Wild West Gold Megaways", bonus_buy: [ 100 ] },
    "vs5strh": { name: "Striking Hot 5", bonus_buy: [] },
    "vs20phoenixf": { name: "Phoenix Forge", bonus_buy: [] },
    "vswayschilheat": { name: "Chilli Heat Megaways", bonus_buy: [ 100 ] },
    "vswayswest": { name: "Mystic Chief", bonus_buy: [] },
    "vs20trsbox": { name: "Treasure Wild", bonus_buy: [ 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 150 ] },
    "vswaysbankbonz": { name: "Cash Bonanza", bonus_buy: [] },
    "vs20smugcove": { name: "Smugglers Cove", bonus_buy: [] },
    "vs20wolfie": { name: "Greedy Wolf", bonus_buy: [] },
    "vs20underground": { name: "Down the Rails", bonus_buy: [] },
    "vswaysbook": { name: "Book of Golden Sands", bonus_buy: [] },
    "vs40mstrwild": { name: "Happy Hooves", bonus_buy: [ 100 ] },
    "vs20fh": { name: "Fire Hot 20", bonus_buy: [] },
    "vs100firehot": { name: "Fire Hot 100", bonus_buy: [] },
    "vs10nudgeit": { name: "Rise of Giza PowerNudge", bonus_buy: [ 80 ] },
    "vswaysyumyum": { name: "Yum Yum Powerways", bonus_buy: [ 100 ] },
    "vs9piggybank": { name: "Piggy Bank Bills", bonus_buy: [] },
    "vs20daydead": { name: "Day of Dead", bonus_buy: [] },
    "vs10runes": { name: "Gates of Valhalla", bonus_buy: [ 100 ] },
    "vswaysxjuicy": { name: "Extra Juicy Megaways", bonus_buy: [ 100 ] },
    "vs25bomb": { name: "Bomb Bonanza", bonus_buy: [] },
    "vswaysjkrdrop": { name: "Tropical Tiki", bonus_buy: [ 100 ] },
    "vs20sh": { name: "Shining Hot 20", bonus_buy: [] },
    "vs20trswild2": { name: "Black Bull", bonus_buy: [ 75 ] },
    "vs1024gmayhem": { name: "Gorilla Mayhem", bonus_buy: [ 80 ] },
    "vs10crownfire": { name: "Crown of Fire", bonus_buy: [] },
    "vs20octobeer": { name: "Octobeer Fortunes", bonus_buy: [ 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 150 ] },
    "vs20bermuda": { name: "John Hunter and the Quest for Bermuda Riches", bonus_buy: [ 100 ] },
    "vs20colcashzone": { name: "Colossal Cash Zone", bonus_buy: [] },
    "vswayselements": { name: "Elemental Gems Megaways", bonus_buy: [] }, // TODO - does not work
    "vs40cleoeye": { name: "Eye of Cleopatra", bonus_buy: [] },
    "vs20pblinders": { name: "Peaky Blinders", bonus_buy: [] },
    "vs20gorilla": { name: "Jungle Gorilla", bonus_buy: [] },
    "vs4096bufking": { name: "Buffalo King", bonus_buy: [ 75 ] },
    "vs3train": { name: "Gold Train", bonus_buy: [] },
    "vs1tigers": { name: "Triple Tigers", bonus_buy: [] },
    "vs25davinci": { name: "Da Vinci's Treasure", bonus_buy: [] },
    "vs25jokerking": { name: "Joker King", bonus_buy: [] },
    "vs40wanderw": { name: "Wild Depths", bonus_buy: [] },
    "cs5triple8gold": { name: "888 Gold", bonus_buy: [] }, // TODO - does not work
    "vs20rome": { name: "Glorious Rome", bonus_buy: [] }, // TODO - does not work
    "vs25sea": { name: "Great Reef", bonus_buy: [] }, // TODO - does not work
    "vs20hockey": { name: "Hockey League", bonus_buy: [] }, // TODO - does not work
    "vs9hockey": { name: "Hockey League Wild Match", bonus_buy: [] },
    "cs3w": { name: "Diamonds are Forever 3 Lines", bonus_buy: [] }, // TODO - does not work
    "vs25dwarves": { name: "Dwarven Gold", bonus_buy: [] }, // TODO - does not work
    "vs13ladyofmoon": { name: "Lady of the Moon", bonus_buy: [] }, // TODO - does not work
    "vs20egypt": { name: "Tales of Egypt", bonus_buy: [] }, // TODO - does not work
    "vs9catz": { name: "The Catfather", bonus_buy: [] },
    "vs30catz": { name: "The Catfather Part II", bonus_buy: [] },
    "vs25goldrush": { name: "Gold Rush", bonus_buy: [] },
    "vs40firehot": { name: "Fire Hot 40", bonus_buy: [] },
    "vs5sh": { name: "Shining Hot 5", bonus_buy: [] },
    "vs40sh": { name: "Shining Hot 40", bonus_buy: [] },
    "vs5firehot": { name: "Fire Hot 5", bonus_buy: [] },
    "vs20wildpix": { name: "Wild Pixies", bonus_buy: [] },
    "vs20eightdragons": { name: "8 Dragons", bonus_buy: [] },
    "vs10bookfallen": { name: "Book of Fallen", bonus_buy: [] },
    "vs243fortseren": { name: "Greek Gods", bonus_buy: [] }, // TODO - does not work
    "vs20santa": { name: "Santa", bonus_buy: [] },
    "vs25kfruit": { name: "Aztec Blaze", bonus_buy: [ 60 ] },
    "vs10tut": { name: "John Hunter and the Book of Tut Respin", bonus_buy: [ 100 ] },
    "vs20mtreasure": { name: "Pirate Golden Age", bonus_buy: [] },
    "vs5trjokers": { name: "Triple Jokers", bonus_buy: [] },
    "vs20kraken": { name: "Release the Kraken", bonus_buy: [ 100 ] },
    "vswayscryscav": { name: "Crystal Cavern Megaways", bonus_buy: [ 80 ] },
    "vs25journey": { name: "Journey to the West", bonus_buy: [] },
    "vs40beowulf": { name: "Beowulf", bonus_buy: [] },
    "vs20godiva": { name: "Lady Godiva", bonus_buy: [] },
    "vs25dragonkingdom": { name: "Dragon Kingdom", bonus_buy: [] },
    "cs3irishcharms": { name: "Irish Charms", bonus_buy: [] },  // TODO - does not work
    "vs5trdragons": { name: "Triple Dragons", bonus_buy: [] },
    "vs20santawonder": { name: "Santa's Wonderland", bonus_buy: [ 100 ] },
    "vs4096magician": { name: "Magician's Secrets", bonus_buy: [ 100 ] },
    "vs20mparty": { name: "Wild Hop and Drop", bonus_buy: [ 100 ] },
    "vs25mmouse": { name: "Money Mouse", bonus_buy: [] },
    "vs5super7": { name: "Super 7s", bonus_buy: [] },
    "vs20fruitparty": { name: "Fruit Party", bonus_buy: [ 100 ] },
    "vs40voodoo": { name: "Voodoo Magic", bonus_buy: [ 80 ] },
    "vs20rainbowg": { name: "Rainbow Gold", bonus_buy: [] },
    "vs50amt": { name: "Aladdin's Treasure", bonus_buy: [] },  // TODO - does not work
    "vs50chinesecharms": { name: "Lucky Dragons", bonus_buy: [] },
    "vs25romeoandjuliet": { name: "Romeo and Juliet (Pragmatic Play)", bonus_buy: [] },
    "vs1dragon8": { name: "888 Dragons", bonus_buy: [] },
    "vs25vegas": { name: "Vegas Nights", bonus_buy: [] },
    "vs10egypt": { name: "Ancient Egypt", bonus_buy: [] },
    "vs25asgard": { name: "Asgard", bonus_buy: [] },
    "vs50safariking": { name: "Safari King", bonus_buy: [] },
    "vs5spjoker": { name: "Super Joker", bonus_buy: [] },
    "vs1024dtiger": { name: "Dragon Tiger", bonus_buy: [] },
    "vs50juicyfr": { name: "Juicy Fruits", bonus_buy: [ 100 ] },
    "vs20muertos": { name: "Muertos Multiplier Megaways", bonus_buy: [ 100 ] },
    "vswaysstrwild": { name: "Candy Stars", bonus_buy: [ 80 ] },
    "vs10snakeladd": { name: "Snakes and Ladders", bonus_buy: [] },
    "vs20swordofares": { name: "Sword of Ares", bonus_buy: [ 100 ] },
    "": { name: "Spin and Score Megaways", bonus_buy: [] }, // TODO - coming soon
    "": { name: "Release the Kraken 2", bonus_buy: [] } // TODO - coming soon
}

// Last updated: 2022.12.03.
yggdrasilSlots = {
    "10080": { name: "10x Rewind" },
    "10025": { name: "12 Trojan Mysteries", BUY_BONUS: 50 },
    "1014": { name: "2 Gods Zeus VS Thor" },
    "10082": { name: "3021 AD The Bounty Hunter Gigablox", BONUS_BUY: 100 }, // cool
    "10223": { name: "60 Second Heist", "BUY_BONUS_F-1": 100 }, // TODO - special
    "1003": { name: "9k Yeti" },
    "10054": { name: "90K Yeti Gigablox", "BB-1": 60, "BB-2": 120, "BB-3": 240, "BB-BIG_GIGA": 150 },
    "10233": { name: "Achilles", BUYIN: 80 },
    "7365": { name: "Age of Asgard" },
    "7332": { name: "Alchymedes" },
    "7372": { name: "Aldo's Journey" },
    "1008": { name: "All Star Knockout" },
    "1027": { name: "Ancient Eclipse" },
    "7384": { name: "Arthur's Fortune" },
    "1020": { name: "Atlantis Megaways" },
    "8308": { name: "Avatars Gateway Guardians" },
    "10096": { name: "Bananaz 10K Ways", buyfeature: 100 }, // cool
    "7354": { name: "Baron Samedi" },
    "7333": { name: "Beauty & The Beast" },
    "7326": { name: "Bicicleta" },
    "10234": { name: "Big Benji Bonanza", BUYIN: 100 },
    "7328": { name: "Big Blox" },
    "1025": { name: "Big Bucks Bandits Megaways", buyfeature: 60 },
    "8306": { name: "Blood Moon Wilds" },
    "10255": { name: "Boilin' Pots", BUY_BONUS: 49.5 },
    "1023": { name: "BountyPop", bonus: 100 },
    "7375": { name: "Brazil Bomba" },
    "10267": { name: "Buffalo Blox Gigablox", higherChanceSpin: { BUYIN: 1.25 } },
    "1028": { name: "Buster Hammer Carnival" },
    "10292": { name: "Calavera Crush", BUY_BONUS: 100, SUPER_BUY_BONUS: 400 },
    "7402": { name: "Carol of the Elves" },
    "1040": { name: "Cauldron" },
    "7357": { name: "Cazino Cosmos" },
    "7308": { name: "Cazino Zeppelin" },
    "10308": { name: "Champion of the Underworld", BUY_BONUS_LOW: 90, BUY_BONUS_HIGH: 1000 },
    "7358": { name: "Champions of Rome", BUY_A_BONUS_TRAINING_CAMP: 50, BUY_A_BONUS_DEATH_MATCH_1: 50, BUY_A_BONUS_DEATH_MATCH_2: 50, BUY_A_BONUS_DEATH_MATCH_3: 50 },
    "1016": { name: "CherryPOP", bonus: 75 },
    "7315": { name: "Chibeasties" },
    "7334": { name: "Chibeasties 2" },
    "10366": { name: "Christmas Plaza Doublemax", BUY_A_BONUS: 100 },
    "1024": { name: "Christmas Tree" },
    "10034": { name: "Crazy Mix" },
    "10064": { name: "Crystal Falls Multimax", BONUS_BUY: 100 },
    "7313": { name: "Cyrus The Virus" },
    "7353": { name: "Dark Vortex" },    // TODO - special
    "1036": { name: "Desperate Dawgs" },
    "7329": { name: "Double Dragons" },
    "7318": { name: "Doubles" },
    "7360": { name: "Dr Fortuno" },
    "7359": { name: "Dwarf Mine" },
    "7346": { name: "Easter Island" },
    "7396": { name: "Easter Island 2" },
    "1026": { name: "El Dorado Infinity Reels" },
    "7324": { name: "Empire Fortune" },
    "10327": { name: "Firekick! MultiMax", BUY_A_BONUS_6: 70 },
    "7386": { name: "Football Glory" },
    "7398": { name: "Frost Queen Jackpots" },
    "7304": { name: "Fruitoids" },
    "10016": { name: "Gargoyle Infinity Reels" },
    "7401": { name: "Gator Gold Gigablox" },
    "10170": { name: "Gator Gold Gigablox Deluxe", BUY_A_BONUS: 60 },
    "7343": { name: "Gem Rocks" },
    "10182": { name: "Gems Infinity Reels" },
    "7397": { name: "Atlantean Gigarise" },
    "1022": { name: "Giza Infinity Reels", buyfeature: 75 },
    "7322": { name: "Golden Fish Tank" },
    "7409": { name: "Golden Fish Tank 2 Gigablox", BUY_BONUS_BASIC: 60, BUY_BONUS_GB: 83.33 },
    "10021": { name: "Golden Gorgon" },
    "10123": { name: "Golden Haul Infinity Reels" },
    "7390": { name: "Hades: Gigablox" },
    "10090": { name: "Hammer of Gods" },
    "7351": { name: "Hanzo's Dojo" },
    "10108": { name: "HippoPop", bonus: 85 },
    "7317": { name: "Holmes and the Stolen Stones" },
    "10172": { name: "Hunters Moon Gigablox", BONUS_BUY: 100 },
    "7392": { name: "Hyperburst" },
    "10171": { name: "Hypernova 10K Ways" },
    "7320": { name: "Incinerator" },
    "7373": { name: "Jackpot Express" },
    "7361": { name: "Jackpot Raiders" },
    "10011": { name: "Jaguar SuperWays" },
    "10007": { name: "Jambo Cash" },
    "10024": { name: "Let It Slide", BUY_BONUS: 57 },
    "1032": { name: "Johnan Legendarian" },
    "7312": { name: "Joker Millions" },
    "7301": { name: "Jokerizer" },
    "10060": { name: "Lollipop", "buy-bonus": 75, "buy-bonus-max": 500 },
    "7337": { name: "Jungle Books" },
    "1041": { name: "Krazy Klimber" },
    "7325": { name: "Legend of the Golden Monkey" },
    "7327": { name: "Legend of the White Snake Lady" },
    "10022": { name: "Legion Hot 1", buyfeature: 50 },
    "7388": { name: "Lightning Joker" },
    "1005": { name: "Lilith's Inferno" },
    "7348": { name: "Lucha Maniacs" },
    "7382": { name: "Lucky Neko: Gigablox" },
    "10046": { name: "Martian Miner Infinity Reels" },
    "10086": { name: "Medusa Hot 1", buy_feature: 100 },
    "10260": { name: "MexoMax Multimax", BUY_A_BONUS: 75, MAX_BUY_A_BONUS: 250 },
    "10302": { name: "Midway Money" },
    "1018": { name: "Moley Moolah!" },
    "7383": { name: "Multifly" },
    "7381": { name: "Neon Rush" },
    "1001": { name: "Niagara Falls" },
    "1002": { name: "Nikola Tesla's Incredible Machine" },
    "7319": { name: "Nirvana" },
    "7355": { name: "Nitro Circus" },
    "1033": { name: "Odin Infinity Reels" },
    "10280": { name: "Of Sabers and Monsters", BUY_BONUS: 80, BUY_RAGNAROK: 500 },
    "8301": { name: "Orient Express" },
    "7345": { name: "Ozwin's Jackpots" },
    "10088": { name: "PapayaPop" },
    "7350": { name: "Penguin City" },
    "10196": { name: "PiggyPop", bonus: 100, fs3: 400 },
    "8309": { name: "Pirates 2: Mutiny" },
    "8304": { name: "Pirates Smugglers Paradise" },
    "1007": { name: "PopRocks" },
    "7335": { name: "Power Plant" },
    "7340": { name: "Pumpkin Smash" },
    "10030": { name: "Pushy Cats", BUY_A_BONUS: 100, MAX_BUY_A_BONUS: 987 },
    "7336": { name: "Rainbow Ryan" },
    "7408": { name: "Raptor Doublemax", BUY_A_BONUS: 100 },
    "7305": { name: "Reef Run" },
    "7376": { name: "Reel Desire" },
    "7342": { name: "Reptoids" },
    "10035": { name: "Robin - Nottingham Raiders" },
    "1038": { name: "Robin - Sherwood Marauders" },
    "1017": { name: "Rock the Cash Bar" },
    "1043": { name: "Royal Dragon Infinity Reels", buyfeature: 66.66 },
    "7371": { name: "Sahara Nights" },
    "10137": { name: "Savanna Roar" },
    "7323": { name: "Seasons" },
    "10174": { name: "Serendipity" },
    "10102": { name: "Siren Song", BUY_BONUS: 127.6 },
    "7339": { name: "Spiña Colada" },
    "7406": { name: "Suncatcher Gigablox" },
    "7338": { name: "Sunny Shores" },
    "10040": { name: "Super Cash Drop" },
    "7330": { name: "Super Heroes" },
    "7391": { name: "Syncronite" },
    "7374": { name: "Temple Stacks" },
    "10010": { name: "Tiki Infinity Reels" },
    "1031": { name: "TikiPop", bonus: 100 },
    "10085": { name: "Tiger Tiger Wild Life" },
    "7310": { name: "The Dark Joker Rizes" },
    "1054": { name: "The Hot Offer" },
    "7364": { name: "The One Armed Bandit" },
    "8303": { name: "The Royal Family" },
    "1035": { name: "Thor Infinity Reels", buyfeature: 100 },
    "7356": { name: "Time Travel Tigers" },
    "10074": { name: "Towering Pays Valhalla", buyfeature_1500: 60 },
    "8302": { name: "Trolls Bridge" },
    "7349": { name: "Tut's Twister" },
    "10194": { name: "Valhalla Saga Thunder of Thor", BUYIN: 60 },
    "7341": { name: "Valley of the Gods" },
    "7389": { name: "Valley of the Gods 2" },
    "7387": { name: "Vault of Fortune" },
    "1030": { name: "Viking Runes" },
    "7331": { name: "Vikings go Berzerk" },
    "10173": { name: "Vikings Go Berzerk Reloaded", BUY_A_BONUS: 75 },
    "7347": { name: "Vikings Go to Hell" },
    "7400": { name: "Vikings go to Valhalla", BUY_WHEEL: 7, BUY_BONUS: 80, BUY_RAGNAROK: 330 },
    "7316": { name: "Vikings Go Wild" },
    "7321": { name: "Wicked Circus" },
    "10298": { name: "Wild Fishin' Wild Ways", INIT_BUY_BONUS: 60 },
    "1042": { name: "Wild Joker Stacks" },
    "1011": { name: "Wild Pops" },
    "7366": { name: "Wild Robo Factory" },
    "7362": { name: "Wilhelm Tell" },
    "10180": { name: "Winfall in Paradise", BONUS_BUY: 120 },
    "7302": { name: "Winterberries" },
    "7352": { name: "Wolf Hunters" },
    "1053": { name: "Word of Thoth", BUY_FREESPINS: 80 },
    "7370": { name: "Yokozuna Clash" },
    "10071": { name: "Lady Merlin Lightning Chase" },
    "10140": { name: "5 Clans: The Final Battle", BONUS_BUY: 100 },
    "10181": { name: "Monster Blox Gigablox", BUY: 70 },
    "10208": { name: "Age of Beasts Infinity Reels" },
    "10111": { name: "Valkyries", BUY: 74 },
    "10177": { name: "Cthulhu" },
    "10199": { name: "Jumbo Jellies", BUY_BONUS: 75 },
    "10211": { name: "Money Mariachi Infinity Reels", buyfeature: 100 },
    "10052": { name: "Xibalba", BUY: 77 },
    "10045": { name: "Steam Spin", BUY_STEAMSPINS: 38, BUY_REDHOTSPINS: 55 },
    "10188": { name: "Cazino Zeppelin Reloaded" },
    "10069": { name: "Time Machine" },
    "10216": { name: "Dead Man’s Fingers" },
    "10097": { name: "Towering Pays Excalibur", buyfeature_1250: 50 },
    "10225": { name: "Tiki Runner 2 DoubleMax", BONUS_BUY: 100 },
    "10214": { name: "Super Cash Drop Gigablox", BUY_BONUS: 75 },
    "10231": { name: "Wild Duel" },
    "10228": { name: "Rise of the Valkyrie Splitz Lightning Chase" },
    "10232": { name: "Hell's Hogs" },
    "10243": { name: "Megapearl Gigablox", buyfeature: 80 },
    "10251": { name: "MonkeyPop", "buy-bonus-1": 100, "buy-bonus-2": 250, "buy-bonus-3": 500 },
    "10239": { name: "WaterBlox Gigablox", BUY_FS_5: 50, BUY_FS_RAND: 122, BUY_FS_20: 500 },
    "10227": { name: "Jokrz Wild UltraNudge" },
    "10235": { name: "4 Fantastic Fish", BUY_BONUS: 75 },
    "10250": { name: "Eye of Persia 2" },
    "10247": { name: "ARRR! 10K Ways", buyfeature: 100 },
    "10229": { name: "Tempered Steel", BONUS_BUY: 100 },    // cool
    "10268": { name: "Wild One", BUY: 70 },
    "10288": { name: "Mega Cash Stacks", BONUS_BUY: 100 },
    "10252": { name: "Professor Clank’s Combinator", buyfeature: 50 },
    "10262": { name: "Dublin Up Doublemax", BONUS_BUY: 100 },
    "10256": { name: "Monsters VS Gigablox" },
    "10285": { name: "Book HOTFIRE" },
    "10215": { name: "Prized Pets Gigablox" },
    "10291": { name: "RagingPop", bonus: 100, bonus2: 500 },
    "10299": { name: "CherryPop Deluxe", bonus: 75, fs3: 300 },
    "10284": { name: "Hillbilly Vegas" },
    "10309": { name: "Voodoo Hex", BUY_FS_7: 52, BUY_FS_RAND: 70, BUY_FS_15: 111 },
    "10303": { name: "Arctic Sorcerer Gigablox" },
    "10310": { name: "Jekyllz Wild UltraNudge", buy_bonus: 125, super_buy_bonus: 350 },
    "10320": { name: "CritterPop", "bonus-buy-1": 125, "bonus-buy-2": 250, "bonus-buy-3": 500 }, // higher chance - ante: 1.25
    "10290": { name: "Florageddon!", buy_bonus: 100, super_buy_bonus: 400 },
    "10305": { name: "7 Gold Gigablox", "BUY_BONUS-1": 60, "BUY_BONUS-2": 120, "BUY_BONUS-3": 240, "BB_BIG_GIGA": 150 },
    "10365": { name: "Cannonade!", BUYBONUS: 100, BUYMAXBONUS: 500 },
    "10383": { name: "Dragon Blox", BUY_BONUS: 100, BUY_FS_RAND: 65 },
    
    "10324": { name: "Gods VS Gigablox", buy_feature: 100 },
    "10375": { name: "Rainbow Power Pots UltraNudge", buy_bonus: 100 },
    "10377": { name: "The Legend of Musashi", BUY_SC: 27, BUY_FS_RAND: 80 },
    "10376": { name: "Festival 10K Ways", buy_feature: 100 },
    "10389": { name: "HipHopPop", "bonus-buy-1": 75, "bonus-buy-3": 300, "bonus-buy-4": 300, "bonus-buy-5": 1000 },
    "10321": { name: "Double Lucky Mushrooms", BONUS_BUY: 65 },
    "10287": { name: "Neon Villains DoubleMax", higherChanceSpin: { GOLDEN_BET: 1.2 }, BUY_BONUS_0: 100, BUY_BONUS_1: 200, BUY_BONUS_2: 500 },
    "10245": { name: "Power of Love" },
    "10395": { name: "Elysian Jackpots" },
    "10379": { name: "Lady Merlin" },
    "10374": { name: "Fury of Hyde Megaways" },
    "10372": { name: "Pharaoh’s Gaze DoubleMax", BONUSBUY: 100 },
    "10378": { name: "Winterberries 2", BUY_BONUS_0: 100, BUY_BONUS_GB_0: 150, BUY_BONUS_1: 200, BUY_BONUS_GB_1: 300 },
    "10384": { name: "3 Lucky Leprechauns", "BUY_BONUS-3": 35, "BUY_BONUS-1": 75, "BUY_BONUS-2": 330 },
    "10405": { name: "Book of Books", BUY_FS_3SC: 120, BUY_FS_4SC: 250, BUY_FS_5SC: 500 },
    "10394": { name: "Bugs Money", higherChanceSpin: { LUCKYBET_BUY: 1.5 } },
    "10403": { name: "Big Bucks Buffalo", buyfeature: 80 },
    "10380": { name: "E-Force", BUY_BONUS_0: 50, BUY_BONUS_1: 500 }
}