{
    "vs20sugarrush": { name: "Sugar Rush", bonus_buy: 100 },
    "vs25wolfgold": { name: "Wolf Gold" },
    "vs20olympgate": { name: "Gates of Olympus", bonus_buy: 100 },
    "vs20fruitsw": { name: "Sweet Bonanza", bonus_buy: 100 },
    "vswaysdogs": { name: "The Dog House Megaways", bonus_buy: 100 },
    "vs20fparty2": { name: "Fruit Party 2", bonus_buy: 100 },
    "vs20doghouse": { name: "The Dog House" },
    "vs20starlight": { name: "Starlight Princess", bonus_buy: 100 },
    "vs25wildspells": { name: "Wild Spells" },
    "vs20bchprty": { name: "Wild Beach Party", bonus_buy: 100 },
    "vs20rhino": { name: "Great Rhino" },
    "vs40pirate": { name: "Pirate Gold", bonus_buy: 0 },
    "vs20goldfever": { name: "Gems Bonanza", bonus_buy: 100 },
    "vs25mustang": { name: "Mustang Gold" },
    "vswaysbufking": { name: "Buffalo King Megaways", bonus_buy: 100 },
    "vs25scarabqueen": { name: "John Hunter and the Tomb of the Scarab Queen" },
    "vs1600drago": { name: "Drago - Jewels of Fortune", bonus_buy: 100 },
    "vs10bookoftut": { name: "John Hunter And The Book Of Tut", bonus_buy: 100 },
    "vs20cleocatra": { name: "Cleocatra", bonus_buy: 100 },
    "vs20midas": { name: "The Hand of Midas", bonus_buy: [100, 200, 300] },
    "vs243fortune": { name: "Caishen's Gold", bonus_buy: [] },
    "vs15diamond": { name: "Diamond Strike", bonus_buy: [] },
    "vs25chilli": { name: "Chilli Heat", bonus_buy: [] },
    "vs5aztecgems": { name: "Aztec Gems", bonus_buy: [] },
    "vs10fruity2": { name: "Extra Juicy", bonus_buy: [] },
    "vs20egypttrs": { name: "Egyptian Fortunes", bonus_buy: [] },
    "vs243lionsgold": { name: "5 Lions Gold", bonus_buy: [] },
    "vs9hotroll": { name: "Hot Chilli", bonus_buy: [] },
    "vs20chicken": { name: "The Great Chicken Escape", bonus_buy: [] },
    "vs1fortunetree": { name: "Tree of Riches", bonus_buy: [] },
    "vs10firestrike": { name: "Fire Strike", bonus_buy: [] },
    "vs20sbxmas": { name: "Sweet Bonanza Xmas", bonus_buy: [ 100 ] },
    "vs40wildwest": { name: "Wild West Gold", bonus_buy: [ 100 ] },
    "vswaysrhino": { name: "Great Rhino Megaways", bonus_buy: 100 },
    "vswayswerewolf": { name: "Curse of the Werewolf Megaways", bonus_buy: [ 100 ] },
    "vs50pixie": { name: "Pixie Wings", bonus_buy: [] },
    "vs25gladiator": { name: "Wild Gladiators", bonus_buy: [] },
    "vs20vegasmagic": { name: "Vegas Magic", bonus_buy: [] },
    "vs7fire88": { name: "Fire 88", bonus_buy: [] },
    "vs5joker": { name: "Joker's Jewels", bonus_buy: [] },
    "vs10madame": { name: "Madame Destiny", bonus_buy: [] },
    "vs1024butterfly": { name: "Jade Butterfly", bonus_buy: [] },
    "vs20leprexmas": { name: "Leprechaun Carol", bonus_buy: [] },
    "vs10vampwolf": { name: "Vampires vs Wolves", bonus_buy: [] },
    "vs20hercpeg": { name: "Hercules and Pegasus", bonus_buy: [] },
    "vs20aladdinsorc": { name: "Aladdin and the Sorcerer", bonus_buy: [] },
    "vs1masterjoker": { name: "Master Joker", bonus_buy: [] },
    "vs40frrainbow": { name: "Fruit Rainbow", bonus_buy: [] },
    "vs75bronco": { name: "Bronco Spirit", bonus_buy: [] },
    "vs25pyramid": { name: "Pyramid King", bonus_buy: [] },
    "vs10goldfish": { name: "Fishin Reels", bonus_buy: [] },
    "vs7monkeys": { name: "7 Monkeys", bonus_buy: [] },
    "vs50aladdin": { name: "3 Genie Wishes", bonus_buy: [] },
    "vs25safari": { name: "Hot Safari", bonus_buy: [] },
    "vs243crystalcave": { name: "Magic Crystals", bonus_buy: [] },
    "vs50kingkong": { name: "Mighty Kong", bonus_buy: [] },
    "vs50hercules": { name: "Hercules Son of Zeus", bonus_buy: [] },
    "vs25queenofgold": { name: "Queen of gold", bonus_buy: [] },
    "vs1024atlantis": { name: "Queen of Atlantis", bonus_buy: [] },
    "vs25kingdoms": { name: "3 Kingdoms – Battle of Red Cliffs", bonus_buy: [] },
    "vs4096jurassic": { name: "Jurassic Giants", bonus_buy: [] },
    "vs7pigs": { name: "7 Piggies", bonus_buy: [] },
    "vs25pandagold": { name: "Panda's Fortune", bonus_buy: [] },
    "vs15fairytale": { name: "Fairytale Fortune", bonus_buy: [] },
    "vs9madmonkey": { name: "Monkey Madness", bonus_buy: [] },
    "vs243lions": { name: "5 Lions", bonus_buy: [] },
    "vs25champ": { name: "The Champions", bonus_buy: [] },
    "vs25peking": { name: "Peking Luck", bonus_buy: [] },
    "vs20leprechaun": { name: "Leprechaun Song", bonus_buy: [] },
    "vs9chen": { name: "Master Chen's Fortune", bonus_buy: [] },
    "vs18mashang": { name: "Treasure Horse", bonus_buy: [] },
    "vs243caishien": { name: "Caishen's Cash", bonus_buy: [] },
    "vs243mwarrior": { name: "Monkey Warrior", bonus_buy: [] },
    "vs8magicjourn": { name: "Magic Journey", bonus_buy: [] },
    "vs4096mystery": { name: "Mysterious", bonus_buy: [] },
    "vs75empress": { name: "Golden Beauty", bonus_buy: [] },
    "vs243dancingpar": { name: "Dance Party", bonus_buy: [] },
    "vs25kfruit": { name: "Aztec Bonanza", bonus_buy: [] },
    "vs40madwheel": { name: "The Wild Machine", bonus_buy: [] },
    "vs10threestar": { name: "Three Star Fortune", bonus_buy: [] },
    "vs117649starz": { name: "Starz Megaways", bonus_buy: [] },
    "vs40streetracer": { name: "Street Racer", bonus_buy: [] }, // ???
    "vs20rhinoluxe": { name: "Great Rhino Deluxe" },
    "vs9aztecgemsdx": { name: "Aztec Gems Deluxe", bonus_buy: [] },
    "vs576treasures": { name: "Wild Wild Riches", bonus_buy: [] },
    "vswayshive": { name: "Star Bounty", bonus_buy: [ 75 ] },
    "vs25walker": { name: "Wild Walker", bonus_buy: [] },
    "vs40pirgold": { name: "Pirate Gold Deluxe", bonus_buy: [ 100 ] },
    "vs10cowgold": { name: "Cowboys Gold", bonus_buy: [] },
    "vs20xmascarol": { name: "Christmas Carol Megaways", bonus_buy: [ 100 ] },
    "vs40spartaking": { name: "Spartan King", bonus_buy: [] },
    "vswayslions": { name: "5 Lions Megaways", bonus_buy: [ 100 ] },
    "vs20emptybank": { name: "Empty the Bank", bonus_buy: [ 80 ] },
    "vs25dwarves_new": { name: "Dwarven Gold Deluxe", bonus_buy: [] },
    "vs25newyear": { name: "Lucky New Year", bonus_buy: [] },
    "vs10mayangods": { name: "John Hunter and the Mayan Gods", bonus_buy: [] },
    "vs20honey": { name: "Honey Honey Honey", bonus_buy: [] },
    "vswaysmadame": { name: "Madame Destiny Megaways", bonus_buy: [ 100 ] },
    "": { name: "Wild Booster", bonus_buy: [] },
    "": { name: "Panther Queen", bonus_buy: [] },
    "": { name: "John Hunter and the Aztec Treasure", bonus_buy: [] },
    "": { name: "Book of Vikings", bonus_buy: [] },
    "": { name: "Chicken Drop", bonus_buy: [] },
    "": { name: "Fortune of Giza", bonus_buy: [] },
    "": { name: "Wild Beach Party", bonus_buy: [] },
    "": { name: "Zombie Carnival", bonus_buy: [] },
    "": { name: "Drago - Jewels of Fortune", bonus_buy: [] },
    "": { name: "Power of Thor Megaways", bonus_buy: [] },
    "": { name: "The Magic Cauldron", bonus_buy: [] },
    "": { name: "Heart of Rio", bonus_buy: [] },
    "": { name: "Barn Festival", bonus_buy: [] },
    "": { name: "North Guardians", bonus_buy: [] },
    "": { name: "Cash Patrol", bonus_buy: [] },
    "": { name: "Chicken Chase", bonus_buy: [] },
    "": { name: "Fire Strike 2", bonus_buy: [] },
    "": { name: "Queen of Gods", bonus_buy: [] },
    "": { name: "5 Lions Dance", bonus_buy: [] },
    "": { name: "Mysterious Egypt", bonus_buy: [] },
    "": { name: "Dragon Kingdom Eyes of Fire", bonus_buy: [] },
    "": { name: "Hot Fiesta", bonus_buy: [] },
    "": { name: "Bounty Gold", bonus_buy: [] },
    "": { name: "Super X", bonus_buy: [] },
    "": { name: "The Ultimate 5", bonus_buy: [] },
    "": { name: "Might of Ra", bonus_buy: [] },
    "": { name: "Drill That Gold", bonus_buy: [] },
    "": { name: "Clover Gold", bonus_buy: [] },
    "": { name: "Goblin Heist Powernudge", bonus_buy: [] },
    "": { name: "The Great Stick-Up", bonus_buy: [] },
    "": { name: "Wild West Gold Megaways", bonus_buy: [] },
    "": { name: "Striking Hot 5", bonus_buy: [] },
    "": { name: "Phoenix Forge", bonus_buy: [] },
    "": { name: "Chilli Heat Megaways", bonus_buy: [] },
    "": { name: "Mystic Chief", bonus_buy: [] },
    "": { name: "Treasure Wild", bonus_buy: [] },
    "": { name: "Cash Bonanza", bonus_buy: [] },
    "": { name: "Smugglers Cove", bonus_buy: [] },
    "": { name: "Greedy Wolf", bonus_buy: [] },
    "": { name: "Down the Rails", bonus_buy: [] },
    "": { name: "Book of Golden Sands", bonus_buy: [] },
    "": { name: "Happy Hooves", bonus_buy: [] },
    "": { name: "Fire Hot 20", bonus_buy: [] },
    "": { name: "Fire Hot 100", bonus_buy: [] },
    "": { name: "Pandas Fortune 2", bonus_buy: [] },
    "": { name: "Rise of Giza PowerNudge", bonus_buy: [] },
    "": { name: "Yum Yum Powerways", bonus_buy: [] },
    "": { name: "Piggy Bank Bills", bonus_buy: [] },
    "": { name: "Day of Dead", bonus_buy: [] },
    "": { name: "Gates of Valhalla", bonus_buy: [] },
    "vswaysxjuicy": { name: "Extra Juicy Megaways", bonus_buy: [ 100 ] },
    "": { name: "Bomb Bonanza", bonus_buy: [] },
    "": { name: "Tropical Tiki", bonus_buy: [] },
    "": { name: "Shining Hot 20", bonus_buy: [] },
    "": { name: "Black Bull", bonus_buy: [] },
    "": { name: "Gorilla Mayhem", bonus_buy: [] },
    "": { name: "Crown of Fire", bonus_buy: [] },
    "": { name: "Octobeer Fortunes", bonus_buy: [] },
    "": { name: "John Hunter and the Quest for Bermuda Riches", bonus_buy: [] },
    "": { name: "Colossal Cash Zone", bonus_buy: [] },
    "": { name: "Elemental Gems Megaways", bonus_buy: [] },
    "": { name: "Eye of Cleopatra", bonus_buy: [] },
    "": { name: "Peaky Blinders", bonus_buy: [] },
    "": { name: "Jungle Gorilla", bonus_buy: [] },
    "": { name: "Buffalo King (Pragmatic Play)", bonus_buy: [] },
    "": { name: "Gold Train (Pragmatic Play)", bonus_buy: [] },
    "": { name: "Triple Tigers (Pragmatic Play)", bonus_buy: [] },
    "": { name: "Da Vinci's Treasure", bonus_buy: [] },
    "": { name: "Joker King (Pragmatic Play)", bonus_buy: [] },
    "": { name: "Wild Depths", bonus_buy: [] },
    "": { name: "888 Gold", bonus_buy: [] },
    "": { name: "Glorious Rome", bonus_buy: [] },
    "": { name: "Great Reef", bonus_buy: [] },
    "": { name: "Hockey League", bonus_buy: [] },
    "": { name: "Hockey League Wild Match", bonus_buy: [] },
    "": { name: "Diamonds are Forever 3 Lines", bonus_buy: [] },
    "": { name: "Dwarven Gold", bonus_buy: [] },
    "": { name: "Lady of the Moon", bonus_buy: [] },
    "": { name: "Tales of Egypt", bonus_buy: [] },
    "": { name: "The Catfather", bonus_buy: [] },
    "": { name: "The Catfather Part II", bonus_buy: [] },
    "": { name: "Gold Rush Scratchcard", bonus_buy: [] },
    "": { name: "Panda Gold Scratchcard", bonus_buy: [] },
    "": { name: "Fire Hot 40", bonus_buy: [] },
    "": { name: "Wolf Gold Scratchcard", bonus_buy: [] },
    "": { name: "Mega Sic Bo", bonus_buy: [] },
    "": { name: "Shining Hot 5", bonus_buy: 0 },
    "": { name: "Shining Hot 40", bonus_buy: 0 },
    "": { name: "Fire Hot 5", bonus_buy: 0 },
    "": { name: "Wild Pixies (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "8 Dragons (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Book of Fallen", bonus_buy: 0 },
    "": { name: "Greek Gods (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Santa (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Aztec Blaze", bonus_buy: 0 },
    "": { name: "John Hunter and the Book of Tut Respin", bonus_buy: 0 },
    "": { name: "Pirate Golden Age", bonus_buy: 0 },
    "": { name: "Triple Jokers (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Release the Kraken (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Crystal Cavern Megaways", bonus_buy: 0 },
    "": { name: "Journey to the West (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Beowulf (Pragmatic)", bonus_buy: 0 },
    "": { name: "Lady Godiva (Pragmatic)", bonus_buy: 0 },
    "": { name: "Dragon Kingdom (Pragmatic)", bonus_buy: 0 },
    "": { name: "Irish Charms (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Triple Dragons (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Santa's Wonderland", bonus_buy: 0 },
    "": { name: "Magician's Secrets", bonus_buy: 0 },
    "": { name: "Wild Hop and Drop", bonus_buy: 0 },
    "": { name: "Diamond Strike Scratchcard", bonus_buy: 0 },
    "": { name: "Bonanza Gold", bonus_buy: 0 },
    "": { name: "Rise of Samurai", bonus_buy: 0 },
    "": { name: "Fu Fu Fu", bonus_buy: 0 },
    "": { name: "Bubble Pop", bonus_buy: 0 },
    "": { name: "Hockey Attack", bonus_buy: 0 },
    "": { name: "Lucky New Year - Tiger Treasures", bonus_buy: 0 },
    "": { name: "Emperor Caishen", bonus_buy: 0 },
    "": { name: "Disco Lady", bonus_buy: 0 },
    "": { name: "Bull Fiesta", bonus_buy: 0 },
    "": { name: "Book of Aztec King", bonus_buy: 0 },
    "": { name: "Rise of Samurai III", bonus_buy: 0 },
    "": { name: "Koi Pond", bonus_buy: 0 },
    "": { name: "Mahjong Panda", bonus_buy: 0 },
    "": { name: "Coffee Wild", bonus_buy: 0 },
    "": { name: "Money Mouse (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Super 7s (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Fruit Party (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Voodoo Magic (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Rainbow Gold (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Aladdin's Treasure (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Bankroll Reload 1 Line", bonus_buy: 0 },
    "": { name: "Bankroll Reload 3 Lines", bonus_buy: 0 },
    "": { name: "Bankroll Reload 5 Lines", bonus_buy: 0 },
    "": { name: "Beauty Salon", bonus_buy: 0 },
    "": { name: "Bee Land", bonus_buy: 0 },
    "": { name: "Berry Flavors 3 Lines", bonus_buy: 0 },
    "": { name: "Big Bang 3 Lines", bonus_buy: 0 },
    "": { name: "Bingo Slot (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Bingo Slot 3 Lines", bonus_buy: 0 },
    "": { name: "Bingo Slot 5 Lines", bonus_buy: 0 },
    "": { name: "Black Diamond (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Black Diamond 1 Line", bonus_buy: 0 },
    "": { name: "Black Diamond 3 Lines", bonus_buy: 0 },
    "": { name: "Black Diamond 5 Lines", bonus_buy: 0 },
    "": { name: "Carnival of Venice", bonus_buy: 0 },
    "": { name: "Casino War (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Cool Stone Age", bonus_buy: 0 },
    "": { name: "Crazy Jungle (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Crazy Pizza 1 Line (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Daytona Gold", bonus_buy: 0 },
    "": { name: "Deuces and Joker (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Deuces Wild (Pragmatic)", bonus_buy: 0 },
    "": { name: "Diablo 13", bonus_buy: 0 },
    "": { name: "Dice and Fire", bonus_buy: 0 },
    "": { name: "Douguie's Delights", bonus_buy: 0 },
    "": { name: "Ducks'n'Eggs", bonus_buy: 0 },
    "": { name: "Fandango's", bonus_buy: 0 },
    "": { name: "Fandango's 1 Line", bonus_buy: 0 },
    "": { name: "Fandango's 3 Lines", bonus_buy: 0 },
    "": { name: "Forest Frenzy", bonus_buy: 0 },
    "": { name: "Forest Treasure (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Fruit Slot (Pragmatic)", bonus_buy: 0 },
    "": { name: "Fruit Slot 1 Line", bonus_buy: 0 },
    "": { name: "Fruit Slot 3 Lines", bonus_buy: 0 },
    "": { name: "Fruit Slot 5 Lines", bonus_buy: 0 },
    "": { name: "Go! Monkey", bonus_buy: 0 },
    "": { name: "Grave Grabbers", bonus_buy: 0 },
    "": { name: "Graveyard Shift", bonus_buy: 0 },
    "": { name: "Happy Circus", bonus_buy: 0 },
    "": { name: "Jacks or Better (Pragmatic)", bonus_buy: 0 },
    "": { name: "Joker Poker (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Keno(Pragmatic)", bonus_buy: 0 },
    "": { name: "Kings and Queens 3 Lines", bonus_buy: 0 },
    "": { name: "KTV", bonus_buy: 0 },
    "": { name: "Lost Gems of Brussels", bonus_buy: 0 },
    "": { name: "Lost Inca's Gold", bonus_buy: 0 },
    "": { name: "Lotto Mania", bonus_buy: 0 },
    "": { name: "Lucky Day at the Races", bonus_buy: 0 },
    "": { name: "Lucky Dragons (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Lucky Fishing", bonus_buy: 0 },
    "": { name: "Lucky Number", bonus_buy: 0 },
    "": { name: "Mad Orchestra", bonus_buy: 0 },
    "": { name: "Merry Bells", bonus_buy: 0 },
    "": { name: "New Tales of Egypt", bonus_buy: 0 },
    "": { name: "Ocean Fantasy", bonus_buy: 0 },
    "": { name: "Orbital Mining", bonus_buy: 0 },
    "": { name: "Quest for the Minotaur", bonus_buy: 0 },
    "": { name: "Red Chili Hunter 5 Lines", bonus_buy: 0 },
    "": { name: "Red White Blue 1 Line", bonus_buy: 0 },
    "": { name: "Red White Blue 3 Lines", bonus_buy: 0 },
    "": { name: "Red White Blue 5 Lines", bonus_buy: 0 },
    "": { name: "Redbeard &amp; Co.", bonus_buy: 0 },
    "": { name: "Reel Gangsters", bonus_buy: 0 },
    "": { name: "Religion of Champions", bonus_buy: 0 },
    "": { name: "Romeo and Juliet (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Russian Attack 3 Lines", bonus_buy: 0 },
    "": { name: "Shia Safavids Treasure", bonus_buy: 0 },
    "": { name: "Slot Dunk", bonus_buy: 0 },
    "": { name: "Sugar Rush Summer Time", bonus_buy: 0 },
    "": { name: "Sugar Rush Valentine's Day", bonus_buy: 0 },
    "": { name: "Sugar Rush Winter", bonus_buy: 0 },
    "": { name: "Summer Party", bonus_buy: 0 },
    "": { name: "Sweet Surprise", bonus_buy: 0 },
    "": { name: "Sweet Surprise 3 Lines", bonus_buy: 0 },
    "": { name: "Transylvania", bonus_buy: 0 },
    "": { name: "Tropical Punch 3 Lines", bonus_buy: 0 },
    "": { name: "Tropical Punch Night Dream 3 Lines", bonus_buy: 0 },
    "": { name: "Viking &amp; Striking", bonus_buy: 0 },
    "": { name: "Voyager's Quest", bonus_buy: 0 },
    "": { name: "Weed Whacker", bonus_buy: 0 },
    "": { name: "Wild Sevens", bonus_buy: 0 },
    "": { name: "Wild Sevens 1 Line", bonus_buy: 0 },
    "": { name: "Wild Sevens 3 Lines", bonus_buy: 0 },
    "": { name: "Wild Sevens 5 Lines", bonus_buy: 0 },
    "": { name: "Witches Cauldron", bonus_buy: 0 },
    "": { name: "888 Dragons (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Vegas Nights (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Star Jackpots", bonus_buy: 0 },
    "": { name: "Gold Rush (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Ancient Egypt (Pragmatic)", bonus_buy: 0 },
    "": { name: "Asgard (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Safari King (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Vikings vs Trolls", bonus_buy: 0 },
    "": { name: "Celtic Gold", bonus_buy: 0 },
    "": { name: "Medusa Strike", bonus_buy: 0 },
    "": { name: "Live Casino Studio", bonus_buy: 0 },
    "": { name: "Vegas Adventures with Mr Green", bonus_buy: 0 },
    "": { name: "Super Joker (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Golden Pig (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "El Dorado The City of Gold", bonus_buy: 0 },
    "": { name: "Super M88", bonus_buy: 0 },
    "": { name: "Bingo Blast (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Boom Box", bonus_buy: 0 },
    "": { name: "Queen of Gold Scratchcard", bonus_buy: 0 },
    "": { name: "Hot Safari Scratchcard", bonus_buy: 0 },
    "": { name: "7 Piggies Scratchcard", bonus_buy: 0 },
    "": { name: "Dragon Tiger (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Wild Wild Wolf", bonus_buy: 0 },
    "": { name: "The Tiger Warrior", bonus_buy: 0 },
    "": { name: "Golden Ox (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Juicy Fruits (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "El Dorado The City of Gold Megaways", bonus_buy: 0 },
    "": { name: "Dragon Tiger Live (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Rise of Samurai Megaways", bonus_buy: 0 },
    "": { name: "Egypt Bonanza", bonus_buy: 0 },
    "": { name: "Devil's 13", bonus_buy: 0 },
    "": { name: "Crazy 7s", bonus_buy: 0 },
    "": { name: "Lucky Dragon Ball", bonus_buy: 0 },
    "": { name: "Money Money Money", bonus_buy: 0 },
    "": { name: "Busy Bees", bonus_buy: 0 },
    "": { name: "Spooky Fortune", bonus_buy: 0 },
    "": { name: "Fruity Blast", bonus_buy: 0 },
    "": { name: "Aztec King Megaways", bonus_buy: 0 },
    "": { name: "Hokkaido Wolf", bonus_buy: 0 },
    "": { name: "Raging Bull (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Andar Bahar (Pragmatic Play)", bonus_buy: 0 },
    "": { name: "Force 1", bonus_buy: 0 },
    "": { name: "Fantastic League", bonus_buy: 0 },
    "": { name: "Greyhound Racing", bonus_buy: 0 },
    "": { name: "Horse Racing", bonus_buy: 0 },
    "": { name: "Book of El Dorado", bonus_buy: 0 },
    "": { name: "Aztec King", bonus_buy: 0 },
    "": { name: "Vbet Sweet Bonanza", bonus_buy: 0 },
    "": { name: "Peaky Blinders 2", bonus_buy: 0 },
    "": { name: "Wolf Gold Power Jackpot", bonus_buy: 0 },
    "": { name: "Muertos Multiplier Megaways", bonus_buy: 0 },
    "": { name: "Candy Stars", bonus_buy: 0 },
    "": { name: "Live Snakes and Ladders", bonus_buy: 0 },
    "": { name: "Sword of Ares", bonus_buy: 0 },
    "": { name: "Cheeky Emperor", bonus_buy: 0 },
    "": { name: "Wildman Super Bonanza", bonus_buy: 0 },
    "": { name: "Towering Fortunes", bonus_buy: 0 },
    "": { name: "Spin and Score Megaways", bonus_buy: 0 },
    "": { name: "Shield of Sparta", bonus_buy: 0 },
    "": { name: "Release the Kraken 2", bonus_buy: 0 },
    "": { name: "Gems of Serengeti", bonus_buy: 0 },
}