pragmaticSlots = {
    "vs20sugarrush": { name: "Sugar Rush", bonus_buy: 100 },
    "vs25wolfgold": { name: "Wolf Gold" },
    "vs20olympgate": { name: "Gates of Olympus", bonus_buy: 100 },
    "vs20fruitsw": { name: "Sweet Bonanza", bonus_buy: 100 },
    "vswaysdogs": { name: "The Dog House Megaways", bonus_buy: 100 },
    "vs20fparty2": { name: "Fruit Party 2", bonus_buy: 100 },
    "vs20doghouse": { name: "The Dog House" },
    "vs20starlight": { name: "Starlight Princess", bonus_buy: 100 },
    "vs25wildspells": { name: "Wild Spells" },
    "vs20bchprty": { name: "Wild Beach Party", bonus_buy: 100 },
    "vs20rhino": { name: "Great Rhino" },
    "vs40pirate": { name: "Pirate Gold", bonus_buy: 0 },
    "vs20goldfever": { name: "Gems Bonanza", bonus_buy: 100 },
    "vs25mustang": { name: "Mustang Gold" },
    "vswaysbufking": { name: "Buffalo King Megaways", bonus_buy: 100 },
    "vs25scarabqueen": { name: "John Hunter and the Tomb of the Scarab Queen" },
    "vs1600drago": { name: "Drago - Jewels of Fortune", bonus_buy: 100 },
    "vs10bookoftut": { name: "John Hunter And The Book Of Tut", bonus_buy: 100 },
    "vs20cleocatra": { name: "Cleocatra", bonus_buy: 100 },
    "vs20midas": { name: "The Hand of Midas", bonus_buy: [100, 200, 300] },
    "vs243fortune": { name: "Caishen's Gold", bonus_buy: [] },
    "vs15diamond": { name: "Diamond Strike", bonus_buy: [] },
    "vs25chilli": { name: "Chilli Heat", bonus_buy: [] },
    "vs5aztecgems": { name: "Aztec Gems", bonus_buy: [] },
    "vs10fruity2": { name: "Extra Juicy", bonus_buy: [] },
    "vs20egypttrs": { name: "Egyptian Fortunes", bonus_buy: [] },
    "vs243lionsgold": { name: "5 Lions Gold", bonus_buy: [] },
    "vs9hotroll": { name: "Hot Chilli", bonus_buy: [] },
    "vs20chicken": { name: "The Great Chicken Escape", bonus_buy: [] },
    "vs1fortunetree": { name: "Tree of Riches", bonus_buy: [] },
    "vs10firestrike": { name: "Fire Strike", bonus_buy: [] },
    "vs20sbxmas": { name: "Sweet Bonanza Xmas", bonus_buy: [ 100 ] },
    "vs40wildwest": { name: "Wild West Gold", bonus_buy: [ 100 ] },
    "vswaysrhino": { name: "Great Rhino Megaways", bonus_buy: 100 },
    "vswayswerewolf": { name: "Curse of the Werewolf Megaways", bonus_buy: [ 100 ] },
    "vs50pixie": { name: "Pixie Wings", bonus_buy: [] },
    "vs25gladiator": { name: "Wild Gladiators", bonus_buy: [] },
    "vs20vegasmagic": { name: "Vegas Magic", bonus_buy: [] },
    "vs7fire88": { name: "Fire 88", bonus_buy: [] },
    "vs5joker": { name: "Joker's Jewels", bonus_buy: [] },
    "vs10madame": { name: "Madame Destiny", bonus_buy: [] },
    "vs1024butterfly": { name: "Jade Butterfly", bonus_buy: [] },
    "vs20leprexmas": { name: "Leprechaun Carol", bonus_buy: [] },
    "vs10vampwolf": { name: "Vampires vs Wolves", bonus_buy: [] },
    "vs20hercpeg": { name: "Hercules and Pegasus", bonus_buy: [] },
    "vs20aladdinsorc": { name: "Aladdin and the Sorcerer", bonus_buy: [] },
    "vs1masterjoker": { name: "Master Joker", bonus_buy: [] },
    "vs40frrainbow": { name: "Fruit Rainbow", bonus_buy: [] },
    "vs75bronco": { name: "Bronco Spirit", bonus_buy: [] },
    "vs25pyramid": { name: "Pyramid King", bonus_buy: [] },
    "vs10goldfish": { name: "Fishin Reels", bonus_buy: [] },
    "vs7monkeys": { name: "7 Monkeys", bonus_buy: [] },
    "vs50aladdin": { name: "3 Genie Wishes", bonus_buy: [] },
    "vs25safari": { name: "Hot Safari", bonus_buy: [] },
    "vs243crystalcave": { name: "Magic Crystals", bonus_buy: [] },
    "vs50kingkong": { name: "Mighty Kong", bonus_buy: [] },
    "vs50hercules": { name: "Hercules Son of Zeus", bonus_buy: [] },
    "vs25queenofgold": { name: "Queen of gold", bonus_buy: [] },
    "vs1024atlantis": { name: "Queen of Atlantis", bonus_buy: [] },
    "vs25kingdoms": { name: "3 Kingdoms – Battle of Red Cliffs", bonus_buy: [] },
    "vs4096jurassic": { name: "Jurassic Giants", bonus_buy: [] },
    "vs7pigs": { name: "7 Piggies", bonus_buy: [] },
    "vs25pandagold": { name: "Panda's Fortune", bonus_buy: [] },
    "vs15fairytale": { name: "Fairytale Fortune", bonus_buy: [] },
    "vs9madmonkey": { name: "Monkey Madness", bonus_buy: [] },
    "vs243lions": { name: "5 Lions", bonus_buy: [] },
    "vs25champ": { name: "The Champions", bonus_buy: [] },
    "vs25peking": { name: "Peking Luck", bonus_buy: [] },
    "vs20leprechaun": { name: "Leprechaun Song", bonus_buy: [] },
    "vs9chen": { name: "Master Chen's Fortune", bonus_buy: [] },
    "vs18mashang": { name: "Treasure Horse", bonus_buy: [] },
    "vs243caishien": { name: "Caishen's Cash", bonus_buy: [] },
    "vs243mwarrior": { name: "Monkey Warrior", bonus_buy: [] },
    "vs8magicjourn": { name: "Magic Journey", bonus_buy: [] },
    "vs4096mystery": { name: "Mysterious", bonus_buy: [] },
    "vs75empress": { name: "Golden Beauty", bonus_buy: [] },
    "vs243dancingpar": { name: "Dance Party", bonus_buy: [] },
    "vs25kfruit": { name: "Aztec Bonanza", bonus_buy: [] },
    "vs40madwheel": { name: "The Wild Machine", bonus_buy: [] },
    "vs10threestar": { name: "Three Star Fortune", bonus_buy: [] },
    "vs117649starz": { name: "Starz Megaways", bonus_buy: [] },
    "vs40streetracer": { name: "Street Racer", bonus_buy: [] }, // ???
    "vs20rhinoluxe": { name: "Great Rhino Deluxe" },
    "vs9aztecgemsdx": { name: "Aztec Gems Deluxe", bonus_buy: [] },
    "vs576treasures": { name: "Wild Wild Riches", bonus_buy: [] },
    "vswayshive": { name: "Star Bounty", bonus_buy: [ 75 ] },
    "vs25walker": { name: "Wild Walker", bonus_buy: [] },
    "vs40pirgold": { name: "Pirate Gold Deluxe", bonus_buy: [ 100 ] },
    "vs10cowgold": { name: "Cowboys Gold", bonus_buy: [] },
    "vs20xmascarol": { name: "Christmas Carol Megaways", bonus_buy: [ 100 ] },
    "vs40spartaking": { name: "Spartan King", bonus_buy: [] },
    "vswayslions": { name: "5 Lions Megaways", bonus_buy: [ 100 ] },
    "vs20emptybank": { name: "Empty the Bank", bonus_buy: [ 80 ] },
    "vs25dwarves_new": { name: "Dwarven Gold Deluxe", bonus_buy: [] },
    "vs25newyear": { name: "Lucky New Year", bonus_buy: [] },
    "vs10mayangods": { name: "John Hunter and the Mayan Gods", bonus_buy: [] },
    "vs20honey": { name: "Honey Honey Honey", bonus_buy: [] },
    "vswaysmadame": { name: "Madame Destiny Megaways", bonus_buy: [ 100 ] },
    "vs20wildboost": { name: "Wild Booster", bonus_buy: [ 75 ] },
    "vs25pantherqueen": { name: "Panther Queen", bonus_buy: [] },
    "": { name: "John Hunter and the Aztec Treasure", bonus_buy: [] },
    "vs10bookviking": { name: "Book of Vikings", bonus_buy: [ 100 ] },
    "vs20chickdrop": { name: "Chicken Drop", bonus_buy: [ 100 ] },
    "vs20amuleteg": { name: "Fortune of Giza", bonus_buy: [] },
    "vs20bchprty": { name: "Wild Beach Party", bonus_buy: [ 100 ] },
    "vswayszombcarn": { name: "Zombie Carnival", bonus_buy: [ 80 ] },
    "vs1600drago": { name: "Drago - Jewels of Fortune", bonus_buy: [ 100 ] },
    "vswayshammthor": { name: "Power of Thor Megaways", bonus_buy: [ 100 ] },
    "vs20magicpot": { name: "The Magic Cauldron", bonus_buy: [] },
    "vs25rio": { name: "Heart of Rio", bonus_buy: [] },
    "vs20farmfest": { name: "Barn Festival", bonus_buy: [ 100 ] },
    "vs50northgard": { name: "North Guardians", bonus_buy: [ 100 ] },
    "vs25copsrobbers": { name: "Cash Patrol", bonus_buy: [] },
    "vs10chkchase": { name: "Chicken Chase", bonus_buy: [] },
    "vs10firestrike2": { name: "Fire Strike 2", bonus_buy: [] },
    "vs10egrich": { name: "Queen of Gods", bonus_buy: [] },
    "vs1024lionsd": { name: "5 Lions Dance", bonus_buy: [] },
    "vs10wildtut": { name: "Mysterious Egypt", bonus_buy: [ 100 ] },
    "vs5drmystery": { name: "Dragon Kingdom Eyes of Fire", bonus_buy: [] },
    "vs25hotfiesta": { name: "Hot Fiesta", bonus_buy: [ 100 ] },
    "vs25btygold": { name: "Bounty Gold", bonus_buy: [] },
    "vs20superx": { name: "Super X", bonus_buy: [] },
    "vs20ultim5": { name: "The Ultimate 5", bonus_buy: [] },
    "vs50mightra": { name: "Might of Ra", bonus_buy: [] },
    "vs20drtgold": { name: "Drill That Gold", bonus_buy: [] },
    "vs20mustanggld2": { name: "Clover Gold", bonus_buy: [] },
    "vs20gobnudge": { name: "Goblin Heist Powernudge", bonus_buy: [ 100 ] },
    "vs20stickysymbol": { name: "The Great Stick-Up", bonus_buy: [] },
    "vswayswildwest": { name: "Wild West Gold Megaways", bonus_buy: [ 100 ] },
    "vs5strh": { name: "Striking Hot 5", bonus_buy: [] },
    "vs20phoenixf": { name: "Phoenix Forge", bonus_buy: [] },
    "vswayschilheat": { name: "Chilli Heat Megaways", bonus_buy: [ 100 ] },
    "vswayswest": { name: "Mystic Chief", bonus_buy: [] },
    "vs20trsbox": { name: "Treasure Wild", bonus_buy: [ 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 150 ] },
    "vswaysbankbonz": { name: "Cash Bonanza", bonus_buy: [] },
    "vs20smugcove": { name: "Smugglers Cove", bonus_buy: [] },
    "vs20wolfie": { name: "Greedy Wolf", bonus_buy: [] },
    "vs20underground": { name: "Down the Rails", bonus_buy: [] },
    "vswaysbook": { name: "Book of Golden Sands", bonus_buy: [] },
    "vs40mstrwild": { name: "Happy Hooves", bonus_buy: [ 100 ] },
    "vs20fh": { name: "Fire Hot 20", bonus_buy: [] },
    "vs100firehot": { name: "Fire Hot 100", bonus_buy: [] },
    "vs10nudgeit": { name: "Rise of Giza PowerNudge", bonus_buy: [ 80 ] },
    "vswaysyumyum": { name: "Yum Yum Powerways", bonus_buy: [ 100 ] },
    "vs9piggybank": { name: "Piggy Bank Bills", bonus_buy: [] },
    "vs20daydead": { name: "Day of Dead", bonus_buy: [] },
    "vs10runes": { name: "Gates of Valhalla", bonus_buy: [ 100 ] },
    "vswaysxjuicy": { name: "Extra Juicy Megaways", bonus_buy: [ 100 ] },
    "vs25bomb": { name: "Bomb Bonanza", bonus_buy: [] },
    "vswaysjkrdrop": { name: "Tropical Tiki", bonus_buy: [ 100 ] },
    "vs20sh": { name: "Shining Hot 20", bonus_buy: [] },
    "vs20trswild2": { name: "Black Bull", bonus_buy: [ 75 ] },
    "vs1024gmayhem": { name: "Gorilla Mayhem", bonus_buy: [ 80 ] },
    "vs10crownfire": { name: "Crown of Fire", bonus_buy: [] },
    "vs20octobeer": { name: "Octobeer Fortunes", bonus_buy: [ 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 150 ] },
    "vs20bermuda": { name: "John Hunter and the Quest for Bermuda Riches", bonus_buy: [ 100 ] },
    "vs20colcashzone": { name: "Colossal Cash Zone", bonus_buy: [] },
    "vswayselements": { name: "Elemental Gems Megaways", bonus_buy: [] }, // TODO - does not work
    "vs40cleoeye": { name: "Eye of Cleopatra", bonus_buy: [] },
    "vs20pblinders": { name: "Peaky Blinders", bonus_buy: [] },
    "vs20gorilla": { name: "Jungle Gorilla", bonus_buy: [] },
    "vs4096bufking": { name: "Buffalo King", bonus_buy: [ 75 ] },
    "vs3train": { name: "Gold Train", bonus_buy: [] },
    "vs1tigers": { name: "Triple Tigers", bonus_buy: [] },
    "vs25davinci": { name: "Da Vinci's Treasure", bonus_buy: [] },
    "vs25jokerking": { name: "Joker King", bonus_buy: [] },
    "vs40wanderw": { name: "Wild Depths", bonus_buy: [] },
    "cs5triple8gold": { name: "888 Gold", bonus_buy: [] }, // TODO - does not work
    "vs20rome": { name: "Glorious Rome", bonus_buy: [] }, // TODO - does not work
    "vs25sea": { name: "Great Reef", bonus_buy: [] }, // TODO - does not work
    "vs20hockey": { name: "Hockey League", bonus_buy: [] }, // TODO - does not work
    "vs9hockey": { name: "Hockey League Wild Match", bonus_buy: [] },
    "cs3w": { name: "Diamonds are Forever 3 Lines", bonus_buy: [] }, // TODO - does not work
    "vs25dwarves": { name: "Dwarven Gold", bonus_buy: [] }, // TODO - does not work
    "vs13ladyofmoon": { name: "Lady of the Moon", bonus_buy: [] }, // TODO - does not work
    "vs20egypt": { name: "Tales of Egypt", bonus_buy: [] }, // TODO - does not work
    "vs9catz": { name: "The Catfather", bonus_buy: [] },
    "vs30catz": { name: "The Catfather Part II", bonus_buy: [] },
    "vs25goldrush": { name: "Gold Rush", bonus_buy: [] },
    "vs40firehot": { name: "Fire Hot 40", bonus_buy: [] },
    "vs5sh": { name: "Shining Hot 5", bonus_buy: [] },
    "vs40sh": { name: "Shining Hot 40", bonus_buy: [] },
    "vs5firehot": { name: "Fire Hot 5", bonus_buy: [] },
    "vs20wildpix": { name: "Wild Pixies", bonus_buy: [] },
    "vs20eightdragons": { name: "8 Dragons", bonus_buy: [] },
    "vs10bookfallen": { name: "Book of Fallen", bonus_buy: [] },
    "vs243fortseren": { name: "Greek Gods", bonus_buy: [] }, // TODO - does not work
    "vs20santa": { name: "Santa", bonus_buy: [] },
    "vs25kfruit": { name: "Aztec Blaze", bonus_buy: [ 60 ] },
    "vs10tut": { name: "John Hunter and the Book of Tut Respin", bonus_buy: [ 100 ] },
    "vs20mtreasure": { name: "Pirate Golden Age", bonus_buy: [] },
    "vs5trjokers": { name: "Triple Jokers", bonus_buy: [] },
    "vs20kraken": { name: "Release the Kraken", bonus_buy: [ 100 ] },
    "vswayscryscav": { name: "Crystal Cavern Megaways", bonus_buy: [ 80 ] },
    "vs25journey": { name: "Journey to the West", bonus_buy: [] },
    "vs40beowulf": { name: "Beowulf", bonus_buy: [] },
    "vs20godiva": { name: "Lady Godiva", bonus_buy: [] },
    "vs25dragonkingdom": { name: "Dragon Kingdom", bonus_buy: [] },
    "cs3irishcharms": { name: "Irish Charms", bonus_buy: [] },  // TODO - does not work
    "vs5trdragons": { name: "Triple Dragons", bonus_buy: [] },
    "vs20santawonder": { name: "Santa's Wonderland", bonus_buy: [ 100 ] },
    "vs4096magician": { name: "Magician's Secrets", bonus_buy: [ 100 ] },
    "vs20mparty": { name: "Wild Hop and Drop", bonus_buy: [ 100 ] },
    "vs25mmouse": { name: "Money Mouse", bonus_buy: [] },
    "vs5super7": { name: "Super 7s", bonus_buy: [] },
    "vs20fruitparty": { name: "Fruit Party", bonus_buy: [ 100 ] },
    "vs40voodoo": { name: "Voodoo Magic", bonus_buy: [ 80 ] },
    "vs20rainbowg": { name: "Rainbow Gold", bonus_buy: [] },
    "vs50amt": { name: "Aladdin's Treasure", bonus_buy: [] },  // TODO - does not work
    "vs50chinesecharms": { name: "Lucky Dragons", bonus_buy: [] },
    "vs25romeoandjuliet": { name: "Romeo and Juliet (Pragmatic Play)", bonus_buy: [] },
    "vs1dragon8": { name: "888 Dragons", bonus_buy: [] },
    "vs25vegas": { name: "Vegas Nights", bonus_buy: [] },
    "vs10egypt": { name: "Ancient Egypt", bonus_buy: [] },
    "vs25asgard": { name: "Asgard", bonus_buy: [] },
    "vs50safariking": { name: "Safari King", bonus_buy: [] },
    "vs5spjoker": { name: "Super Joker", bonus_buy: [] },
    "vs1024dtiger": { name: "Dragon Tiger", bonus_buy: [] },
    "vs50juicyfr": { name: "Juicy Fruits", bonus_buy: [ 100 ] },
    "vs20muertos": { name: "Muertos Multiplier Megaways", bonus_buy: [ 100 ] },
    "vswaysstrwild": { name: "Candy Stars", bonus_buy: [ 80 ] },
    "vs10snakeladd": { name: "Snakes and Ladders", bonus_buy: [] },
    "vs20swordofares": { name: "Sword of Ares", bonus_buy: [ 100 ] },
    "": { name: "Spin and Score Megaways", bonus_buy: [] }, // TODO - coming soon
    "": { name: "Release the Kraken 2", bonus_buy: [] } // TODO - coming soon
}